import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './normalize.css';
import './reset.css';
import '../styles/globals.scss';
import { GlobalNavbar } from './_component/GlobalNavbar';
import { LocalNavbar } from './_component/LocalNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavbar />
        <LocalNavbar />
        {children}
        {modal}
      </body>
    </html>
  );
}
