import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './normalize.css';
import './reset.css';
import '../styles/globals.scss';
import { GlobalNavbar } from './_component/GlobalNavbar';
import { LocalNavbar } from './_component/LocalNavbar';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <GlobalNavbar />
        <LocalNavbar />
        {children}
        {modal}
      </body>
    </html>
  );
}
